version: "3"
services:
  develop:
    image: node:latest
    container_name: develop
    working_dir: /app
    environment:
      - REDIS_ENDPOINT=Redis
      - PORT=3000
    depends_on:
      - Redis
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./:/app
    tty: true

  Redis:
    image: redis:latest
    container_name: Redis
    ports:
      - 6379:6379
    restart: always
